### ISSUE TITLE
Apple App Store Allowed?

### ISSUE THREAD

**Issue by wayneforrest** [mavris/MacFinder#2]
Will Apple allow this library to be used on the App Store?

Are any private calls made? Is sysctl private?
And the FreeBSD headers seems like a hack, will this go unnoticed?

**Comment by mavris** [comment]
Hi,
I am not sure if Apple will allow it. I am using it for a personal app which is not uploaded to App Store. My plan is to add it on one of my existing apps and see what happens. Let me know if you find something before me. By the way, a lot of apps on App Store are able to show Mac Address. Unless they have developed their own algorithm, this is the only "known" way to find a MAC Address on iOS

**Comment by wayneforrest** [comment]
Thanks for the feedback Mavris. I will post back if I find some useful info.
