### ISSUE TITLE
How to make it work with iOS 10.2?

### ISSUE THREAD

**Issue by leonfu** [mavris/MacFinder#4]
for iOS 10.2, all the mac addresses return 02:00:00:00:00:00, so sad

@mavris

**Comment by mavris** [comment]
Take a look at this issue. We opened a bug report at Apple. https://github.com/mavris/MMLanScan/issues/3 Although that is not a bug they might come back with an alternative

**Comment by mavris** [comment]
MacFinder is updated (1.2.0) and fixed this issue
