### ISSUE TITLE
Randomised mac address.

### ISSUE THREAD

**Issue by pradeepdgit** [mavris/MacFinder#5]
This is a new security fix Apple has done in iOS8. According to this the Mac address keeps changing so that no Developer can track the iPhone device. 

Please let me know what is the effect of this security fix on your code?

http://appleinsider.com/articles/14/06/09/mac-address-randomization-joins-apples-heap-of-ios-8-privacy-improvements

**Comment by mavris** [comment]
This code works for 10.2.1 but it won't work for 10.3.
