### ISSUE TITLE
 'net/route.h' file not found in xcode 9

### ISSUE THREAD

**Issue by vinayakb73** [mavris/MacFinder#9]
Hi, I am getting below error after I updated my xcode to xcode 9. The error is on MacFinder.h ,line number 12.

`/Users/srswebsolutions/Desktop/VinayakProjects/referenceProject/for-es-local/Pods/MMLanScan/MMLanScan/External Libs/MacFinder/MacFinder.h:12:10: 'net/route.h' file not found`

**Comment by mavris** [comment]
I will look into this but I would like to let you know that MacFinder won't work for iOS 11+

**Comment by 19kka** [comment]
@vinayakb73 u can try this in MacFinder.h: 

```objc
#if TARGET_IPHONE_SIMULATOR
#include <net/route.h>
#else
#include "route.h"
#endif
```

**Comment by mavris** [comment]
Hi guys, I wont finx MacFinder since is useless for iOS 11. You can find the MacFinder.h and MacFinder.m inside the [MMLanScan](https://github.com/mavris/MMLanScan) folder

**Comment by toddanglin** [comment]
For added context for those that run in to this same problem, this thread explains in more detail what happened in iOS 11 that now makes it impossible to get MAC addresses: https://github.com/mavris/MMLanScan/issues/23
